#!/bin/bash
#set -x

scriptdir=`dirname $0`
cd "$scriptdir"
here=`pwd`
cd "../../../../.."
vondadir=`pwd`
depclp=`mvn dependency:build-classpath`
cd "$here"
# Done from java, only for test purposes
#$vondadir/compile -c config.yml AllYouCanDo.rudi
rm -rf target
mkdir -p target/classes
export CLASSPATH="${depclp}:${vondadir}/library/target/classes:target/classes"
#echo $CLASSPATH
javac -d target/classes \
      src/main/java/mini/WrapperClass.java \
      src/main/generated/mini/AllYouCanDo.java \
      src/main/generated/mini/sub/Sub.java \
      src/main/generated/mini/sub/Breaks.java \
      src/main/generated/mini/sub/SameLevel.java \
      src/main/generated/mini/sub/sub/SubSub.java \
