# This is a default HFC config file, which needs to be adapted to contain the
# application specific ontologies and namespaces. It contains the current
# default setup for VOnDA (transaction time, quadruples) and equivalence
# reduction
minArgs: 3
maxArgs: 4
noOfCores: 4
#noOfAtoms: 100000
#noOfTuples: 500000
shortIsDefault: true
#persistenceFile=/tmp/tuples.nt
eqReduction: true
characterEncoding: UTF-8
addTimestamps: [ 0 ]

# further options for the future,
# e.g., character encoding, persistent output file name, etc.

namespaces:
  # namespaces for XSD, RDF, RDFS, and OWL are already defined
  dial: http://www.dfki.de/lt/onto/common/dialogue.owl#

tupleFiles:
  # the axiomatic triples for OWL-Horst w/ EQ reduction
  - default/default.eqred.nt
  # the dialogue act ontology, as used in VOnDA for DA <-> RDF translation
  - dialogue/dialogue.nt

ruleFiles:
  # we need special rules for transaction time (mixture of triples/quadruples)
  - rules/default.eqred.quads.rdl
