name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: bkiefer/vonda@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag vonda-full:$(date +%s)
